### ISSUE TITLE
suggestion：assign specific clientID

### ISSUE THREAD

**Issue by zronghui** [leonwind/cli2cloud#26]
This log overwrites the last one.
The main purpose is to view the log of commands executed on a regular basis. Alternatively, you can allow a user to log in to see the execution of all his commands.

**Comment by leonwind** [comment]
Hi,
Thanks for the suggestion!
I was already thinking about a user account system so you can view your personal client IDs and further personal features.
However, for now I don't think I want to increase the complexity of the tool by that much. But I will keep it in mind that there is some request for that :)

Furthermore, I also don't think letting the user choose their client ID is a good idea since it would add a lot of frustration to try out common IDs, which other clients have already used.

For your use case I think it would be the best if all your regular commands just log to one or multiple common log files and that you have a further (simple python) script to read the content of all those scripts and send the content to cli2cloud. With this approach you should have only one client ID.

Let me know what you think or if I misunderstood something! :)
